figures:
  dir: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo/reports/figures
  processed: null
  raw: null
  variables: null
final:
  dir: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo/data/final
  name: final.csv
  path: ${final.dir}/${final.name}
  processed: null
  raw: null
  variables: null
mlflow_PASSWORD: 9ecdb1317a8f2ee28a0903ad3820410a56fe763e
mlflow_USERNAME: ctabet
mlflow_tracking_ui: https://dagshub.com/ctabet/mlops_repos2.mlflow
model:
  dir: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo/models
  name: LogisticRegression
  path: ${model.dir}/${model.name}
  processed: null
  raw: null
  variables: null
processed:
  dir: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo/data/processed
  processed: null
  raw: null
  variables: null
  x_test:
    name: x_test.csv
    path: ${processed.dir}/${processed.x_test.name}
    processed: null
    raw: null
    variables: null
  x_train:
    name: x_train.csv
    path: ${processed.dir}/${processed.x_train.name}
    processed: null
    raw: null
    variables: null
  y_test:
    name: y_test.csv
    path: ${processed.dir}/${processed.y_test.name}
    processed: null
    raw: null
    variables: null
  y_train:
    name: y_train.csv
    path: ${processed.dir}/${processed.y_train.name}
    processed: null
    raw: null
    variables: null
raw:
  Label: target
  Numeric_cols_to_scale:
  - age
  - trestbps
  - chol
  - thalach
  - oldpeak
  path: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo/data/raw/heart.csv
  processed: null
  raw: null
  variables: null
variables:
  categorical_variables:
  - sex
  - cp
  - fbs
  - restecg
  - exang
  - slope
  - ca
  - thal
  - target
  continuous_variables:
  - age
  - trestbps
  - chol
  - thalach
  - oldpeak
  processed: null
  raw: null
  root_path: C:/charbel tabet/charbel/mlops_repos/mlops_training_repo
  variables: null
